VALIDATOR_LIST:
  -   host: node0.rchain.coop
      grpc_port: 40401
      http_port: 40403
      pub_key: key1
      isHTTPS: false
VALIDATOR_REQUEST_TIMEOUT:
  2
VALIDATORS_TTL:
  10
HOST:
  0.0.0.0
PORT:
  7070
