VALIDATOR_LIST:
  -   host: node0.rchain.coop
      grpc_port: 40401
      http_port: 40403
      pub_key: key1
      isHTTPS: false
VALIDATOR_REQUEST_TIMEOUT:
  2
VALIDATORS_TTL:
  10
DATABASE:
  type: lmdb
  path: /path/to/database
  map_size: 500048576
TARGET_RNODE_HOST:
  rnode.host
TARGET_RNODE_PORT:
  40401
TARGET_RNODE_HTTP_PORT:
  40403
USE_HTTPS:
  false
HOST:
  0.0.0.0
PORT:
  7070
NUM_CORE:
  4
LOG_PATH:
  /path/to/log.log
CACHE_TTL:
  60
TARGET_TESTNET_HOST:
  testnet.host
TARGET_TESTNET_PORT:
  40401
TESTNET_FAUCET_TTL:
  7200
TESTNET_FAUCET_SHARDID:
  testnet
TESTNET_FAUCET_PRIVATE_KEY:
  privatekey
TESTNET_FAUCET_AMOUNT:
  10000000000